# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GO_VERSION: 1.13.4
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: UnitTests
    condition: in(variables['test-type'],'','unit-test') # Run if test-type is not set or if test-type is 'unit-test'
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 90
    steps:
    - template: azp-dependencies-mod.yml
    - checkout: self
      path: 'go/src/github.com/hyperledger/fabric'
    - script: ./ci/scripts/setup_hsm.sh
      displayName: Install SoftHSM
    - script: make basic-checks native unit-test
      displayName: Run checks and Unit Tests

  - job: IntegrationTests
    condition: eq(variables['test-type'],'integration-test') # Run only if test-type is 'integration-test'
    pool:
      vmImage: ubuntu-18.04
    strategy:
      parallel: 6
    timeoutInMinutes: 240
    steps:
    - template: azp-dependencies-mod.yml
    - checkout: self
      path: 'go/src/github.com/hyperledger/fabric'
    - script: make integration-test
      displayName: Run Integration Tests
